// Copyright Eigi Chin

#pragma once

#include "NativeGameplayTags.h"

// Ability Type

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Type_Action_Tactical_Main);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Type_Action_Tactical_Sub);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Type_Action_Tactical_Ultimate);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Type_Passive_ChangeQuickBarSlot);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Type_Action_Weapon_Attack);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Type_Action_Weapon_AltAttack);

// Input Type

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Ability_Tactical_Main);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Ability_Tactical_Sub);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Ability_Tactical_Ultimate);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Ability_QuickSlot_Next);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Ability_QuickSlot_Back);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Ability_QuickSlot_Select);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Ability_QuickSlot_Drop);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Ability_Weapon_Fire);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Ability_Weapon_AltFire);
